// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"pg68fy1ghc","name":"encoder","description":"Encoding Job Trigger","endpoint":"https://pg68fy1ghc.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/encoder","/encoder/123"]}];
var aws_cognito_identity_pool_id = 'us-east-1:131c67c9-b2dd-4080-8094-40625d3723f0';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'streamingr-hosting-mobilehub-1777251661';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd29ejeh8bv38is.cloudfront.net';
var aws_mobile_analytics_app_id = '333c8f5514bc4203aa403ae2631dcba6';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '9eb56ca2-e3d1-430f-9a2e-e2d4a1894fb9';
var aws_project_name = 'StreamingR10';
var aws_project_region = 'us-east-1';
var aws_resource_bucket_name = 'streamingr-deployments-mobilehub-1777251661';
var aws_resource_name_prefix = 'streamingr-mobilehub-1777251661';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
