// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"pg68fy1ghc","name":"encoder","description":"Encoding Job Trigger","endpoint":"https://pg68fy1ghc.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/encoder","/encoder/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:131c67c9-b2dd-4080-8094-40625d3723f0',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'streamingr-hosting-mobilehub-1777251661',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd29ejeh8bv38is.cloudfront.net',
    'aws_mobile_analytics_app_id': '333c8f5514bc4203aa403ae2631dcba6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '9eb56ca2-e3d1-430f-9a2e-e2d4a1894fb9',
    'aws_project_name': 'StreamingR10',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'streamingr-deployments-mobilehub-1777251661',
    'aws_resource_name_prefix': 'streamingr-mobilehub-1777251661',
}

export default awsmobile;
