export const REGISTER_CHANGE_NAME = "REGISTER_CHANGE_NAME";
export const REGISTER_CHANGE_EMAIL = "REGISTER_CHANGE_EMAIL";
export const REGISTER_CHANGE_PASSWORD = "REGISTER_CHANGE_PASSWORD";
export const REGISTER_CHANGE_CONFIRM_PASSWORD = "REGISTER_CHANGE_CONFIRM_PASSWORD";
export const REGISTER_SET_USER = "REGISTER_SET_USER";
export const REGISTER_RESET_FORM = "REGISTER_RESET_FORM";