export const SET_TOKEN = "SET_TOKEN";
export const SET_LIST = "SET_LIST";
export const SET_DETAILS = "SET_DETAILS";
export const SET_PHARMACIES = "SET_PHARMACIES";
export const SET_LEVEL = "SET_LEVEL";
export const SET_INDEX = "SET_INDEX";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const RESET_STATE = "RESET_STATE";

export const SET_PRESCRIPTION = "SET_PRESCRIPTION";
export const SET_PRESCRIPTION_FORM = "SET_PRESCRIPTION_FORM";
export const SET_PRESCRIPTION_DOSAGE = "SET_PRESCRIPTION_DOSAGE";
export const SET_PRESCRIPTION_QUANTITY = "SET_PRESCRIPTION_QUANTITY";
export const SET_PRESCRIPTION_COST = "SET_PRESCRIPTION_COST";
export const SET_PHARMACY_NAME = "SET_PHARMACY_NAME";
